import{a as B,S as E,i as s}from"./assets/vendor-rOMtvQ2t.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const R="51405853-c477ae5482bbe39eb607a142d",P="https://pixabay.com/api/";async function m(n,o=1){const e={key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await B.get(P,{params:e})).data}const f=document.querySelector(".gallery"),p=document.getElementById("loader"),g=document.getElementById("load-more"),S=new E(".gallery a");function h(n){const o=n.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",o),S.refresh()}function $(){f.innerHTML=""}function y(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function w(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const b=document.querySelector(".form"),I=b.elements["search-text"],M=document.getElementById("load-more");let d="",i=1,u=0;const v=15;b.addEventListener("submit",async n=>{n.preventDefault();const o=I.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight",timeout:3e3});return}d=o,i=1,$(),c(),y();try{const e=await m(d,i);if(u=e.totalHits,e.hits.length===0){s.error({title:"No Results",message:"No images found. Try another keyword.",position:"topRight",timeout:3e3});return}h(e.hits),u>v&&w()}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3})}finally{L()}});M.addEventListener("click",async()=>{i+=1,c(),y();try{const n=await m(d,i);h(n.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),i*v>=u?(c(),s.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):w()}catch{s.error({title:"Error",message:"Failed to load more images.",position:"topRight",timeout:3e3})}finally{L()}});
//# sourceMappingURL=index.js.map
