import{a as B,S as E,i}from"./assets/vendor-rOMtvQ2t.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const R="51405853-c477ae5482bbe39eb607a142d",P="https://pixabay.com/api/";async function m(n,o=1){const e={key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await B.get(P,{params:e})).data}const f=document.querySelector(".gallery"),p=document.getElementById("loader"),y=document.getElementById("load-more"),S=new E(".gallery a");function g(n){const o=n.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",o),S.refresh()}function $(){f.innerHTML=""}function h(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function b(){y.classList.remove("hidden")}function a(){y.classList.add("hidden")}const w=document.querySelector(".form"),I=w.elements["search-text"],M=document.getElementById("load-more");let d="",s=1,u=0;const v=15;a();w.addEventListener("submit",async n=>{n.preventDefault();const o=I.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight",timeout:3e3});return}d=o,s=1,$(),a(),h();try{const e=await m(d,s);if(u=e.totalHits,e.hits.length===0){i.error({title:"No Results",message:"No images found. Try another keyword.",position:"topRight",timeout:3e3});return}g(e.hits),s*v<u?b():a()}catch{i.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3})}finally{L()}});M.addEventListener("click",async()=>{s+=1,a(),h();try{const n=await m(d,s);g(n.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),s*v>=u?(a(),i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):b()}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight",timeout:3e3})}finally{L()}});
//# sourceMappingURL=index.js.map
